# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'openssl', '>=2.0'
gem 'json', '2.3.0'
# gem 'base64'